### ISSUE TITLE
python version, cudnn version 

### ISSUE THREAD

**Issue by xuronaweizida** [yuke93/RL-Restore#3] opened 2018-08-01 04:45 UTC
Thanks for sharing your code.  The test mode works fine on my computer, but the error comes out in the train mode, with the error in the "optimizer.py" . the detail error is: 
 line 151, in _get_processor
    if v.op.type == "VarHandleOp": AttributeError: 'dict_values' object has no attribute 'op'

May be it is caused by the software updating. Could you please tell me your python version, cudnn version  and tensorflow version.?

**Comment by yuke93** [comment] 2018-08-06 04:48
Hi @xuronaweizida,

Here is my environment setting:
Python 2.7
TensorFlow 1.3 or 1.4
CUDA 8.0
cuDNN 5.1

**Comment by yuke93** [comment] 2018-08-06 07:01
I believe this issue is caused by the difference of dict between Python 2/3. Now Python3 compatibility is added and this issue should be fixed.

**Closed** 2018-08-06 07:02 UTC
